# Upptime Configuration for Speisekarte
# https://upptime.js.org/docs/configuration

owner: maxxxor
repo: speisekarte-uptime
userDisplayName: maxxxor

sites:
  - name: Gastmenue trattoria-da-marco
    url: https://speisekarte-ten.vercel.app/m/trattoria-da-marco
    expectedResponseTime: 5000

  - name: Login-Seite
    url: https://speisekarte-ten.vercel.app/login
    expectedResponseTime: 5000

status-website:
  cname: false
  baseUrl: /speisekarte-uptime
  name: Speisekarte Status

notifications:
  - type: github-issues

assignees:
  - maxxxor
