name: Response Time CI
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  graphs:
    name: Generate graphs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Upptime
        uses: upptime/uptime-monitor@master
        with:
          UPPTIME_GH_APP_TOKEN: ${{ secrets.GH_PAT }}
          command: graphs
        env:
          ACTIONS_STEP_DEBUG: false
