name: Static Site CI
on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    name: Deploy status page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Upptime
        uses: upptime/uptime-monitor@master
        with:
          UPPTIME_GH_APP_TOKEN: ${{ secrets.GH_PAT }}
          command: site
        env:
          ACTIONS_STEP_DEBUG: false
