name: Uptime CI
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  uptime:
    name: Check uptime
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Upptime
        uses: upptime/uptime-monitor@master
        with:
          command: update
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          ACTIONS_STEP_DEBUG: false
